### ISSUE TITLE
Not working on kali

### ISSUE THREAD

**Issue by jedai47** [richardlehane/xmltool#1]
I have the following issue:
```
./xmltool.go -fix output.xml > good.xml
./xmltool.go: 1: package: not found
./xmltool.go: 4: Syntax error: newline unexpected (expecting ")")
```

**Comment by richardlehane** [comment]
I've updated the install instruction in the README. Try installing with `go install github.com/richardlehane/xmltool@latest`

This should install a xmltool binary into your go/bin folder.

Assuming the go/bin folder is in your path, you can then run with `./xmltool -fix output.xml > good.xml`
